# keyword_analyzer.py
import google.generativeai as genai
import re
from collections import Counter

def configure_genai():
    """Configure Gemini API."""
    genai.configure(api_key="AIzaSyAN6hW728nRG6ITJWMSJYQzSrkaEDeseOk")  # Replace with your actual API key

def generate_keywords_with_weightage(question, model_answer, marks):
    """Generate weighted keywords using Gemini AI and fallback extraction."""
    configure_genai()
    model = genai.GenerativeModel('gemini-pro')

    # Generate AI-based answer
    response = model.generate_content(question)
    ai_generated_answer = response.text.strip() if response.text else ""

    prompt = f"""
    Analyze this question and its answers to provide keywords with their importance weightage (0.1-100):
    
    Question: {question}
    Model Answer: {model_answer}
    AI Generated Answer: {ai_generated_answer}
    Marks: {marks}

    For lower marks question(1 marks), consider the answer has one main keyword and rank that keyword with highest weightage
    Rules for keyword weightage:
    2. Core concept keywords should have higher weightage
    3. Supporting concept keywords should have medium weightage
    4. Additional detail keywords should have lower weightage
    5. If the question asks for full form of something then that full form will be the highest weightage keyword
    6. If the keyword generated by the model is already present in the question do not consider that keyword
    
    Provide output in this exact format (one per line):
    keyword1: weightage
    keyword2: weightage
    keyword3: weightage
    """

    response = model.generate_content(prompt)
    keywords_text = response.text.strip()

    # Parse keywords into dictionary
    keyword_weights = {}
    for line in keywords_text.split('\n'):
        if ':' in line:
            keyword, weight = line.split(':')
            keyword = keyword.strip().lower()
            try:
                weight = float(weight.strip())
                weight = max(1, min(100, weight))  # Ensure within valid range
                keyword_weights[keyword] = weight
            except ValueError:
                continue

    return keyword_weights

if __name__ == "__main__":
    question = input("Enter the question: ")
    model_answer = input("Enter the model answer: ")
    marks = int(input("Enter the marks (1-20): "))

    keywords = generate_keywords_with_weightage(question, model_answer, marks)
    print("\nExtracted Keywords with Weightage:")
    print(f"Keyword_weights is: {keywords}")
    for keyword, weight in keywords.items():
        print(f"{keyword}: {weight:.2f}")
